export const FETCH_TASKS = "FETCH_TASKS";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILED = "FETCH_TASKS_FAILED";
export const FILTER_TASK = "FILTER_TASK";
export const FILTER_TASK_SUCCESS = "FILTER_TASK_SUCCESS";
export const ADD_TASKS = "ADD_TASKS";
export const ADD_TASKS_SUCCESS = "ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILED = "ADD_TASKS_FAILED";

export const SET_TASK_EDITING = "SET_TASK_EDITING";

export const UPDATE_TASKS = "UPDATE_TASKS";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILED = "UPDATE_TASKS_FAILED";

export const DELETE_TASKS = "DELETE_TASKS";
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_FAILED = "DELETE_TASKS_FAILED";
